language: java

before_install: mvn install -DskipTests=true -DfinalName=sample-$TRAVIS_TAG
install: mvn test

deploy:
  provider: releases
  api_key:
    secure: iKJHl5QlCfYFT4k3yNDV2w1KnW4g+Ms/KlKbO54HP2qT6NUtRDdV+MyCHq6Q3D1fEyfc11dtVfUFxkcO59AT3QClp+7k1kuZtF6rt4Gs8x9nrSFe/nN2t+SwDTiwzAIqD4mgintAHJiVFez07Q/dCwNEyXtVYivLBHy5Gg9EKNw=
  file: target/sample-$TRAVIS_TAG.war
  on:
    tags: true
